#!/usr/bin/env python3
"""Bundle the config panel's ES modules (panel/*.js) into the inline <script> of docs/index.html.

The modules are the source; docs/index.html carries the generated bundle so the page is one self-contained
file (it opens from disk, where browsers refuse to load modules, and GitHub Pages serves it as-is).

    python3 tools/build_panel.py           rewrite the bundle in docs/index.html
    python3 tools/build_panel.py --check   exit 1 if docs/index.html is out of date

Every top-level name is unique across the modules and imports never rename, so bundling is: drop the import
lines and `export` keywords and concatenate the modules into one strict function scope, in the order the browser
evaluates them (depth-first post-order of the imports, starting at app.js).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "panel"
HTML = ROOT / "docs" / "index.html"
ENTRY = "app.js"
HEADER = "// GENERATED by tools/build_panel.py from panel/*.js -- edit those and run `make panel`; this block is overwritten."
IMPORT = re.compile(r"import \{ [\w$, ]+ \} from '\./([\w-]+\.js)';$")
EXPORT = re.compile(r"export (?=(async function|function|const|let|class) )")
DECL = re.compile(r"(?:export )?(?:async )?(?:function\*?|const|let|var|class)\s+([\w$]+)")


def fail(msg):
    sys.exit(f"build_panel: {msg}")


def load(name):
    path = SRC / name
    if not path.is_file():
        fail(f"panel/{name} not found")
    deps, body = [], []
    for n, line in enumerate(path.read_text().split("\n"), 1):
        if line.startswith("import"):
            m = IMPORT.fullmatch(line.rstrip())
            if not m:
                fail(f"panel/{name}:{n}: only single-line `import {{ a, b }} from './x.js';` is supported")
            deps.append(m.group(1))
            continue
        if line.startswith("export"):
            if not EXPORT.match(line):
                fail(f"panel/{name}:{n}: only `export function/const/let/class` is supported")
            line = line[len("export "):]
        if "</script" in line.lower():
            fail(f"panel/{name}:{n}: `</script` would end the inline script early")
        body.append(line)
    return deps, "\n".join(body).strip("\n")


def bundle():
    order, mods, seen = [], {}, set()

    def visit(name):
        seen.add(name)
        mods[name] = load(name)
        for dep in mods[name][0]:
            if dep not in seen:
                visit(dep)
        order.append(name)

    visit(ENTRY)
    unused = sorted(p.name for p in SRC.glob("*.js") if p.name not in seen)
    if unused:
        fail("not imported from app.js: " + ", ".join(unused))
    owner = {}
    for name in order:
        for line in mods[name][1].split("\n"):
            m = DECL.match(line)
            if m:
                if m.group(1) in owner:
                    fail(f"top-level `{m.group(1)}` declared in both {owner[m.group(1)]} and {name}")
                owner[m.group(1)] = name
    parts = [f"// ---- panel/{name} ----\n{mods[name][1]}" for name in order]
    return f"<script>\n{HEADER}\n(()=>{{\n\"use strict\";\n\n" + "\n\n".join(parts) + "\n})();\n</script>"


def main():
    html = HTML.read_text()
    m = re.search(r"<script>\n" + re.escape(HEADER) + r"\n.*?</script>", html, re.S) or re.search(
        r'<script type="module" src="js/app.js"></script>', html
    )
    if not m:
        fail("no generated <script> block found in docs/index.html")
    out = html[: m.start()] + bundle() + html[m.end():]
    if "--check" in sys.argv[1:]:
        if out != html:
            fail("docs/index.html is out of date with panel/*.js -- run `make panel`")
        print("docs/index.html is up to date")
        return
    if out != html:
        HTML.write_text(out)
        print("docs/index.html rebuilt")
    else:
        print("docs/index.html already up to date")


if __name__ == "__main__":
    main()
