#!/usr/bin/env python3
"""Generate panel/sc2_mesh.js (the 3D view's controller model) from Valve's published Steam Controller shell.

    pip install numpy fast-simplification
    python3 tools/sc2_mesh.py sc_solid_stl_20260429.stl [triangles]

The STL comes from https://gitlab.steamos.cloud/SteamHardware/SteamController (CC BY-NC-SA 4.0, Valve). It is
decimated to a few thousand triangles, moved into the SC2 sensor frame the panel uses (+x right, +y forward,
+z up; the CAD file has +y up and +z toward the player), centred, and tagged per vertex as shell, trackpad or
stick cap so the view can tint them.
"""
import base64
import sys
from pathlib import Path

import fast_simplification
import numpy as np

OUT = Path(__file__).resolve().parents[1] / "panel" / "sc2_mesh.js"
STICKS = [(-22.4, -32.5), (22.4, -32.5)]  # cap centres (mm, SC2 frame, before centring)
PADS = [(-30.4, -61.8, -8.3), (30.4, -61.8, 8.3)]  # centre (mm) and twist (degrees); ~31 mm rounded squares


def main():
    src = sys.argv[1]
    tris = int(sys.argv[2]) if len(sys.argv) > 2 else 8000
    d = Path(src).read_bytes()
    n = int.from_bytes(d[80:84], "little")
    rec = np.frombuffer(d, np.dtype([("n", "<f4", 3), ("v", "<f4", (3, 3)), ("a", "<u2")]), count=n, offset=84)
    pts, inv = np.unique(np.round(rec["v"].reshape(-1, 3), 4), axis=0, return_inverse=True)
    v = np.c_[pts[:, 0], -pts[:, 2], pts[:, 1]].astype(np.float64)  # CAD (x, y up, z back) -> SC2 (x, y fwd, z up)

    # inside each pad's groove, top surface only (the bottom shell is 30+ mm lower)
    def pad(v, cx, cy, deg):
        c, s = np.cos(np.radians(deg)), np.sin(np.radians(deg))
        dx, dy = v[:, 0] - cx, v[:, 1] - cy
        return (np.abs(dx * c + dy * s) < 14.5) & (np.abs(-dx * s + dy * c) < 14.5) & (v[:, 2] > -20)

    v, f = fast_simplification.simplify(v, inv.reshape(-1, 3), target_reduction=1 - tris / n)

    mat = np.zeros(len(v), np.uint8)
    # the pads' dot texture decimates into noise: flatten each pad onto its best-fit plane (the view also gives
    # each pad a single normal, which hides the slivers decimation folds over it)
    for p in PADS:
        sel = pad(v, *p)
        a = np.c_[v[sel, 0], v[sel, 1], np.ones(sel.sum())]
        v[sel, 2] = a @ np.linalg.lstsq(a, v[sel, 2], rcond=None)[0]
        mat[sel] = 1
    for cx, cy in STICKS:
        mat[(np.hypot(v[:, 0] - cx, v[:, 1] - cy) < 11.5) & (v[:, 2] > 0.5)] = 2

    v -= (v.min(0) + v.max(0)) / 2
    pos = np.round(v * 10).astype("<i2")  # 0.1 mm
    b64 = lambda a: base64.b64encode(a.tobytes()).decode()
    OUT.write_text(
        "// GENERATED by tools/sc2_mesh.py -- Steam Controller shell, decimated.\n"
        "// Model: Valve Corporation, https://gitlab.steamos.cloud/SteamHardware/SteamController\n"
        "// Licensed CC BY-NC-SA 4.0 (https://creativecommons.org/licenses/by-nc-sa/4.0/), not the AGPL of the\n"
        "// rest of the panel. Not affiliated with or endorsed by Valve.\n"
        "// Vertices: s16 x,y,z in 0.1 mm (SC2 frame, centred); material per vertex: 0 shell, 1 trackpad, 2 stick;\n"
        "// triangles: u16 vertex indices.\n"
        f'export const SC2_POS = "{b64(pos)}";\n'
        f'export const SC2_MAT = "{b64(mat)}";\n'
        f'export const SC2_IDX = "{b64(f.astype("<u2"))}";\n'
    )
    print(f"{OUT}: {len(v)} vertices, {len(f)} triangles, {OUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
